services:
    TweedeGolf\PrometheusClient\Storage\ApcuAdapter:
        class: TweedeGolf\PrometheusClient\Storage\ApcuAdapter

    TweedeGolf\PrometheusClient\Storage\ApcAdapter:
        class: TweedeGolf\PrometheusClient\Storage\ApcAdapter

    TweedeGolf\PrometheusBundle\Controller\MetricsController:
        class: Tweedegolf\PrometheusBundle\Controller\MetricsController
        arguments:
            - "@TweedeGolf\PrometheusClient\CollectorRegistry"
